### ISSUE TITLE
The plugin keeps telling me that it's generating dummies

### ISSUE THREAD

**Issue by janhendrickx** [am-impact/amseed#1]
I've set up this plugin to start generating dummy content, but there seems to be a problem since my craftCMS menu has an new item "generating dummys" that won't go away as you can see in the screenshot.
I've uninstalled and deleted the plugin in Craft, and I've deleted it via FTP, and cleared my caches (just to make sure everything was deleted). I'm guessing this is a small issue, but worth mentioning. 
![screen shot 2016-03-30 at 09 09 27](https://cloud.githubusercontent.com/assets/17985717/14134381/28d5f3d8-f657-11e5-96e4-dcf582fdab77.png)

**Comment by hubertprein** [comment]
@janhendrickx Seems that the top task is stuck. You're best of to go to the tasks table in the database, and remove that task so the rest will function just fine :)

This hasn't happend to me, so if this happens again, could you notify me what you did and what your settings are?

**Comment by janhendrickx** [comment]
Hi Hubert. Thanks for the tip, removing those worked perfect (I'm new to craft - I used to work with Drupal). I can't remember exactly what I did, but chances are that I'm gonna use it again soon and if it happens again I'll post it here!
